#!/usr/bin/env bash
# load-secrets.sh - secrets.list に列挙した環境変数だけを ~/.secrets へ取り込む。
#
#   - ホスト env（docker-compose.yml の environment: 経由）にあればそれを優先し、
#     ~/.secrets には書かない（compose がそのまま供給するため）。
#   - 未設定の名前だけ bws のシークレット（key == その名前）から取得して ~/.secrets に書く。
#
# ~/.secrets は Dockerfile が仕込んだ /etc/profile.d/secrets.sh 経由で
# ログインシェル / 対話シェル起動時に自動 source される。
#
# 使い方 (コンテナ内):
#   .devcontainer/load-secrets.sh                    # 既定リストを使用
#   .devcontainer/load-secrets.sh path/to/list       # リストを指定
#   BWS_PROJECT=my-project .devcontainer/load-secrets.sh
set -euo pipefail

LIST_FILE="${1:-/workspace/.devcontainer/secrets.list}"
SECRETS_FILE="$HOME/.secrets"
BWS_PROJECT="${BWS_PROJECT:-}"   # non-secret: SM project name or GUID; empty = all

trap 'rm -f "$SECRETS_FILE.tmp"' EXIT

[ -r "$LIST_FILE" ] || { echo "Error: secrets list not found: $LIST_FILE" >&2; exit 1; }

# 1. 許可リストを読む（1 行 1 名前、# コメント・空行・前後空白を許容）
NAMES=()
while IFS= read -r raw; do
    name="${raw%%#*}"
    name="$(printf '%s' "$name" | tr -d '[:space:]')"
    [ -n "$name" ] || continue
    if [[ "$name" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]]; then
        NAMES+=("$name")
    else
        echo "Warning: skipping '$name' (not a valid environment variable name)." >&2
    fi
done < "$LIST_FILE"

if [ "${#NAMES[@]}" -eq 0 ]; then
    echo "No variable names listed in $LIST_FILE - nothing to do."
    exit 0
fi

# 2. bws から一括取得。値は base64 で受けて改行/引用符に耐える。
#    bws を参照できない（トークン無し / bws 不在 / 認証失敗）ときは、既存の ~/.secrets を
#    上書きして壊さないよう、ここで何もせず終了する（ホスト env は compose 経由で別途供給される）。
if [ -z "${BWS_ACCESS_TOKEN:-}" ] || ! command -v bws >/dev/null 2>&1; then
    echo "Note: BWS_ACCESS_TOKEN not set (or bws missing) - leaving $SECRETS_FILE untouched." >&2
    exit 0
fi

project_arg=()
if [ -n "$BWS_PROJECT" ]; then
    if [[ "$BWS_PROJECT" =~ ^[0-9a-fA-F-]{36}$ ]]; then
        project_arg=("$BWS_PROJECT")
    else
        pid=$(bws project list -o json | jq -r --arg n "$BWS_PROJECT" '.[] | select(.name == $n) | .id')
        [ -n "$pid" ] || { echo "Error: Secrets Manager project '$BWS_PROJECT' not found." >&2; exit 1; }
        project_arg=("$pid")
    fi
fi

if ! bws project list -o none >/dev/null 2>&1; then
    echo "Warning: bws authentication failed - leaving $SECRETS_FILE untouched." >&2
    exit 1
fi

declare -A BWS_SECRETS=()
while read -r key b64; do
    [ -n "$key" ] || continue
    BWS_SECRETS["$key"]="$(printf '%s' "$b64" | base64 -d)"
done < <(bws secret list "${project_arg[@]}" -o json |
    jq -r '.[] | select(.key != null and .value != null and .value != "") | "\(.key) \(.value | @base64)"')

# 3. 前回このスクリプトが書いた値をこのプロセス内で unset する。
#    こうすると以降の printenv は「真にホスト由来の変数」だけを反映し、
#    再実行時に bws 由来の古い値をホスト由来と誤認しない。
if [ -f "$SECRETS_FILE" ]; then
    while read -r prev; do
        [ -n "$prev" ] && unset "$prev" || true
    done < <(grep -oE '^export [A-Za-z_][A-Za-z0-9_]*' "$SECRETS_FILE" | awk '{print $2}')
fi

# 4. 名前ごとにマージ。ホスト env 優先、無ければ bws。
host_names=()
bws_names=()
skipped_names=()
{
    echo "# Auto-generated by .devcontainer/load-secrets.sh - do not edit manually"
    for name in "${NAMES[@]}"; do
        if printenv "$name" >/dev/null 2>&1; then
            host_names+=("$name")            # compose の environment: が供給。ここには書かない。
        elif [ -n "${BWS_SECRETS[$name]+x}" ]; then
            printf 'export %s=%q\n' "$name" "${BWS_SECRETS[$name]}"
            bws_names+=("$name")
        else
            skipped_names+=("$name")
        fi
    done
} > "$SECRETS_FILE.tmp"

mv "$SECRETS_FILE.tmp" "$SECRETS_FILE"
chmod 600 "$SECRETS_FILE"

# 5. サマリー
echo ""
echo "--- Summary ---"
echo "host env : ${#host_names[@]}   bws : ${#bws_names[@]}   skipped : ${#skipped_names[@]}"
for n in "${host_names[@]}";    do echo "  [host] $n"; done
for n in "${bws_names[@]}";     do echo "  [bws]  $n"; done
for n in "${skipped_names[@]}"; do echo "  [skip] $n  (not in host env or bws)" >&2; done
echo ""
echo "Wrote $SECRETS_FILE (loaded automatically in new shells; run 'source ~/.secrets' for the current one)."
