#!/bin/bash
set -e

SECRETS_FILE="$HOME/.secrets"

# Install Bitwarden CLI if not present
if ! command -v bw &>/dev/null; then
    echo "Installing Bitwarden CLI..."
    npm install -g @bitwarden/cli
fi

# Login if unauthenticated
STATUS=$(bw status | jq -r '.status')
if [ "$STATUS" = "unauthenticated" ]; then
    echo "Not logged in. Starting Bitwarden login..."
    bw login
fi

# Unlock and capture session token
SESSION=$(bw unlock --raw)
if [ -z "$SESSION" ]; then
    echo "Error: Bitwarden unlock failed." >&2
    exit 1
fi
export BW_SESSION="$SESSION"

bw sync --session "$BW_SESSION" > /dev/null
echo "Bitwarden synced."

# Resolve api_keys folder ID
FOLDER_ID=$(bw list folders --session "$BW_SESSION" | jq -r '.[] | select(.name == "api_keys") | .id')
if [ -z "$FOLDER_ID" ]; then
    echo "Error: Folder 'api_keys' not found." >&2
    exit 1
fi

# Fetch items in folder
ITEMS=$(bw list items --folderid "$FOLDER_ID" --session "$BW_SESSION")
ITEM_COUNT=$(echo "$ITEMS" | jq 'length')
echo "Found $ITEM_COUNT items in 'api_keys'."

# Write secrets to ~/.secrets (login.password > notes > matched custom field)
{
    echo "# Auto-generated by initialize_security.sh — do not edit manually"
    echo "$ITEMS" | jq -r '.[] |
        .name as $name |
        (
            if .login.password != null and .login.password != "" then .login.password
            elif .notes != null and .notes != "" then .notes
            else (
                (.fields // []) |
                map(select(
                    .name != null and
                    (.name | ascii_downcase | test("value|api_key|secret|password|key"))
                )) |
                first |
                .value // empty
            )
            end
        ) as $value |
        select($value != null and $value != "") |
        "export \($name)=\"\($value)\""'
} > "$SECRETS_FILE"
chmod 600 "$SECRETS_FILE"

SAVED=$(grep -c '^export ' "$SECRETS_FILE" || true)
echo ""
echo "--- Summary ---"
echo "$SAVED secret(s) written to $SECRETS_FILE"
echo "Run: source $SECRETS_FILE  (or restart your shell)"
