#!/data/data/com.termux/files/usr/bin/bash
set -e

BASHRC="$HOME/.bashrc"
BASH_PROFILE="$HOME/.bash_profile"

[ -f "$BASHRC" ]      && cp "$BASHRC"      "${BASHRC}.bak"
[ -f "$BASH_PROFILE" ] && cp "$BASH_PROFILE" "${BASH_PROFILE}.bak"

cat > "$BASHRC" << 'EOF'
alias la="ls -a"
alias ll="ls -l"
alias lf="ls -al"
EOF

cat > "$BASH_PROFILE" << 'EOF'
export SCRIPTS="$HOME/storage/documents/termux/scripts"
export TERMUX="$HOME/storage/documents/termux"
export DOCUMENTS="$HOME/storage/documents"
export DOWNLOADS="$HOME/storage/downloads"

# Load API keys from ~/.secrets if it exists
# Generated by installer/setup_security.sh
if [ -f "$HOME/.secrets" ]; then
    source "$HOME/.secrets"
fi
EOF

echo "Done: .bashrc and .bash_profile have been overwritten."
echo "Run: source ~/.bash_profile"
