#!/data/data/com.termux/files/usr/bin/bash
# initialize_security.sh - Sync Bitwarden Secrets Manager secrets to a local file
set -euo pipefail

SECRETS_FILE="$HOME/.secrets"
BWS_PROJECT="${BWS_PROJECT:-}"        # non-secret: SM project name or GUID; empty = all
BWS_VERSION="${BWS_VERSION:-2.1.0}"   # keep in sync with the devcontainer Dockerfile
TMP="${TMPDIR:-/tmp}"

trap 'rm -f "$SECRETS_FILE.tmp"' EXIT

# Dependencies (jq / curl / unzip)
_install_pkg() {
    if command -v pkg &>/dev/null; then pkg install -y "$@"; else apt-get update -y && apt-get install -y "$@"; fi
}
for dep in jq curl unzip; do
    command -v "$dep" &>/dev/null || { echo "--- Installing $dep ---"; _install_pkg "$dep"; }
done

# 1. Install the Bitwarden Secrets Manager CLI (bws) if missing.
if ! command -v bws &>/dev/null; then
    echo "Installing Bitwarden Secrets Manager CLI (bws ${BWS_VERSION})..."
    case "$(uname -m)" in
        aarch64) triple="aarch64-unknown-linux-musl" ;;
        x86_64)  triple="x86_64-unknown-linux-musl" ;;
        *) echo "Error: unsupported architecture $(uname -m)" >&2; exit 1 ;;
    esac
    mkdir -p "$HOME/.local/bin"
    curl -fsSL "https://github.com/bitwarden/sdk-sm/releases/download/bws-v${BWS_VERSION}/bws-${triple}-${BWS_VERSION}.zip" -o "$TMP/bws.zip"
    unzip -o "$TMP/bws.zip" bws -d "$HOME/.local/bin/"
    chmod +x "$HOME/.local/bin/bws"
    rm -f "$TMP/bws.zip"
fi
export PATH="$HOME/.local/bin:$PATH"

# 2. Access token: environment (CI) or hidden prompt. Process-scoped, never stored.
if [ -z "${BWS_ACCESS_TOKEN:-}" ]; then
    read -rsp "Bitwarden Secrets Manager access token: " BWS_ACCESS_TOKEN
    echo
    export BWS_ACCESS_TOKEN
fi
[ -n "${BWS_ACCESS_TOKEN:-}" ] || { echo "Error: no access token supplied." >&2; exit 1; }

# 3. Verify auth
if ! bws project list -o none >/dev/null 2>&1; then
    echo "Error: bws authentication failed. Check the access token." >&2
    exit 1
fi

# 4. Resolve the optional project filter (name or GUID)
PROJECT_ARG=()
if [ -n "$BWS_PROJECT" ]; then
    if [[ "$BWS_PROJECT" =~ ^[0-9a-fA-F-]{36}$ ]]; then
        PROJECT_ARG=("$BWS_PROJECT")
    else
        pid=$(bws project list -o json | jq -r --arg n "$BWS_PROJECT" '.[] | select(.name == $n) | .id')
        [ -n "$pid" ] || { echo "Error: Secrets Manager project '$BWS_PROJECT' not found." >&2; exit 1; }
        PROJECT_ARG=("$pid")
    fi
fi

# 5. Write ~/.secrets (key -> var name, value -> value; @sh = safe shell quoting).
#    Keys that are not valid shell identifiers are skipped with a warning.
echo "Updating $SECRETS_FILE..."
secrets_json=$(bws secret list "${PROJECT_ARG[@]}" -o json)

echo "$secrets_json" | jq -r '
    .[] | select(.key != null)
        | select((.key | test("^[A-Za-z_][A-Za-z0-9_]*$")) | not)
        | .key' | while read -r bad; do
    [ -n "$bad" ] && echo "Warning: skipping '$bad' (not a valid environment variable name)." >&2
done

{
    echo "# Auto-generated by initialize_security.sh (bws) - do not edit manually"
    echo "$secrets_json" | jq -r '
        .[] | select(.key != null and .value != null and .value != "")
            | select(.key | test("^[A-Za-z_][A-Za-z0-9_]*$"))
            | "export \(.key)=\(.value | @sh)"'
} > "$SECRETS_FILE.tmp"
mv "$SECRETS_FILE.tmp" "$SECRETS_FILE"
chmod 600 "$SECRETS_FILE"
echo "Security initialization finished. Secrets saved to $SECRETS_FILE."
