#!/data/data/com.termux/files/usr/bin/bash
# setup_security.sh - Fetches secrets from Bitwarden and saves to ~/.secrets
set -e

# Check if bw is installed
if ! command -v bw &> /dev/null; then
    echo "Error: Bitwarden CLI (bw) is not installed."
    echo "Please install it first: pkg install nodejs-lts && npm install -g @bitwarden/cli"
    exit 1
fi

# Bitwarden Login/Unlock logic
# Use python3 to parse status since jq might be missing
STATUS=$(bw status | python3 -c "import sys, json; print(json.load(sys.stdin).get('status', 'unauthenticated'))")

if [ "$STATUS" = "unauthenticated" ]; then
    echo "Not logged in. Running bw login..."
    bw login
fi

# Ensure session is unlocked
BW_SESSION=$(bw unlock --raw)
if [ -z "$BW_SESSION" ]; then
    echo "Error: Failed to get Bitwarden session."
    exit 1
fi
export BW_SESSION

# Sync with online
echo "Syncing Bitwarden..."
bw sync --session "$BW_SESSION"

SECRETS_FILE="$HOME/.secrets"
echo "Writing secrets to $SECRETS_FILE..."

# Initialize or clear file
echo "# Generated by setup_security.sh" > "$SECRETS_FILE"
chmod 600 "$SECRETS_FILE"

# Function to fetch and write
save_secret() {
    local key=$1
    local bw_name=$2
    echo "Fetching $bw_name from Bitwarden..."
    # 'bw get password' is used for passwords/keys
    local val=$(bw get password "$bw_name" --session "$BW_SESSION")
    if [ -n "$val" ]; then
        echo "export $key='$val'" >> "$SECRETS_FILE"
        echo "Saved: $key"
    else
        echo "Warning: Bitwarden item '$bw_name' not found."
    fi
}

# Secrets to fetch (Matching setup_security.ps1)
save_secret "PERPLEXITY_API_KEY" "PERPLEXITY_API_KEY"
save_secret "GITHUB_PERSONAL_ACCESS_TOKEN" "GITHUB_PERSONAL_ACCESS_TOKEN"
save_secret "BRIGHTDATA_API_TOKEN" "BRIGHTDATA_API_TOKEN"
save_secret "HF_TOKEN" "HF_TOKEN"
save_secret "GW_MCP_CLIENT_ID" "GW_MCP_CLIENT_ID"
save_secret "GW_MCP_CLIENT_SECRET" "GW_MCP_CLIENT_SECRET"

echo ""
echo "Done: Secrets saved to $SECRETS_FILE (chmod 600)."
echo "Make sure your ~/.bash_profile sources this file."
