$chocoPackages = @(
    "vscode",
    "materialicon-vscode",
    "bitwarden-chrome",
    "spacedesk-server",
    "python39",
    "python310",
    "python311",
    "python312",
    "python313",
    "gsudo",
    "vim",
    "nvm",
    "uv",
    "jq",
    "curl",
    "tree",
    "ngrok",
    "wireshark",
    "procmon",
    "pdf24",
    "visualstudio2022-workload-vctools"  # MSVC linker/toolset: `cargo install bws` needs link.exe
)
