#!/bin/bash
set -euo pipefail

if [ "$EUID" -eq 0 ]; then
    echo "Error: Do not run this script with sudo. Run as your regular user:" >&2
    echo "  bash ./wsl-setup/initialize_security.sh" >&2
    exit 1
fi

SECRETS_FILE="$HOME/.secrets"
BWS_PROJECT="${BWS_PROJECT:-}"        # non-secret: SM project name or GUID; empty = all
BWS_VERSION="${BWS_VERSION:-2.1.0}"   # keep in sync with the devcontainer Dockerfile

trap 'rm -f "$SECRETS_FILE.tmp"' EXIT

# 1. Install the Bitwarden Secrets Manager CLI (bws) if missing.
#    Prebuilt static musl binary from the sdk-sm releases (same source as the devcontainer).
if ! command -v bws &>/dev/null; then
    echo "Installing Bitwarden Secrets Manager CLI (bws ${BWS_VERSION})..."
    case "$(uname -m)" in
        x86_64)  triple="x86_64-unknown-linux-musl" ;;
        aarch64) triple="aarch64-unknown-linux-musl" ;;
        *) echo "Error: unsupported architecture $(uname -m)" >&2; exit 1 ;;
    esac
    mkdir -p "$HOME/.local/bin"
    curl -fsSL "https://github.com/bitwarden/sdk-sm/releases/download/bws-v${BWS_VERSION}/bws-${triple}-${BWS_VERSION}.zip" -o /tmp/bws.zip
    unzip -o /tmp/bws.zip bws -d "$HOME/.local/bin/"
    chmod +x "$HOME/.local/bin/bws"
    rm -f /tmp/bws.zip
fi
export PATH="$HOME/.local/bin:$PATH"

# 2. Access token. A machine-account token grants read access to one Secrets
#    Manager project - never the personal vault. Taken from the environment (CI)
#    or pasted interactively, and never written to disk.
if [ -z "${BWS_ACCESS_TOKEN:-}" ]; then
    read -rsp "Bitwarden Secrets Manager access token: " BWS_ACCESS_TOKEN
    echo
    export BWS_ACCESS_TOKEN
fi
[ -n "${BWS_ACCESS_TOKEN:-}" ] || { echo "Error: no access token supplied." >&2; exit 1; }

# 3. Verify auth
if ! bws project list -o none >/dev/null 2>&1; then
    echo "Error: bws authentication failed. Check the access token." >&2
    exit 1
fi

# 4. Resolve the optional project filter (name or GUID)
PROJECT_ARG=()
if [ -n "$BWS_PROJECT" ]; then
    if [[ "$BWS_PROJECT" =~ ^[0-9a-fA-F-]{36}$ ]]; then
        PROJECT_ARG=("$BWS_PROJECT")
    else
        pid=$(bws project list -o json | jq -r --arg n "$BWS_PROJECT" '.[] | select(.name == $n) | .id')
        [ -n "$pid" ] || { echo "Error: Secrets Manager project '$BWS_PROJECT' not found." >&2; exit 1; }
        PROJECT_ARG=("$pid")
    fi
fi

# 5. Write ~/.secrets. SM secrets carry a real key/value pair; @sh quotes the
#    value safely for `source`. Keys that are not valid shell identifiers are skipped.
secrets_json=$(bws secret list "${PROJECT_ARG[@]}" -o json)

echo "$secrets_json" | jq -r '
    .[] | select(.key != null)
        | select((.key | test("^[A-Za-z_][A-Za-z0-9_]*$")) | not)
        | .key' | while read -r bad; do
    [ -n "$bad" ] && echo "Warning: skipping '$bad' (not a valid environment variable name)." >&2
done

{
    echo "# Auto-generated by initialize_security.sh (bws) - do not edit manually"
    echo "$secrets_json" | jq -r '
        .[] | select(.key != null and .value != null and .value != "")
            | select(.key | test("^[A-Za-z_][A-Za-z0-9_]*$"))
            | "export \(.key)=\(.value | @sh)"'
} > "$SECRETS_FILE.tmp"
mv "$SECRETS_FILE.tmp" "$SECRETS_FILE"
chmod 600 "$SECRETS_FILE"

# 6. Ensure ~/.secrets is auto-loaded in new shells
# shellcheck disable=SC2016  # literal line written verbatim into ~/.bashrc
BASHRC_SOURCE_LINE='[ -f "$HOME/.secrets" ] && source "$HOME/.secrets"'
if ! grep -qF '.secrets' "$HOME/.bashrc" 2>/dev/null; then
    {
        echo ""
        echo "# Load API keys (written by initialize_security.sh)"
        echo "$BASHRC_SOURCE_LINE"
    } >> "$HOME/.bashrc"
    echo "Added source line to \$HOME/.bashrc"
else
    echo "\$HOME/.bashrc already sources \$HOME/.secrets - skipped."
fi

SAVED=$(grep -c '^export ' "$SECRETS_FILE" || true)
echo ""
echo "--- Summary ---"
echo "$SAVED secret(s) written to $SECRETS_FILE"
if [ "$SAVED" -gt 0 ]; then
    echo ""
    echo "Loaded variables:"
    grep '^export ' "$SECRETS_FILE" | sed 's/^export \([^=]*\)=.*/\1/' | while read -r varname; do
        echo "  $varname"
    done
fi
echo ""
echo "Run: source ~/.bashrc  (または新しいターミナルを開いてから Claude Code を再起動)"
