#!/bin/bash
set -e

if [ "$EUID" -eq 0 ]; then
    echo "Error: Do not run this script with sudo. Run as your regular user:" >&2
    echo "  bash ./installer/initialize_security.sh" >&2
    exit 1
fi

# Load nvm so that npm/node installed via nvm are available
export NVM_DIR="${NVM_DIR:-$HOME/.nvm}"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

SECRETS_FILE="$HOME/.secrets"

read -rsp "Bitwarden master password: " BW_PASSWORD
echo
export BW_PASSWORD

# Install Bitwarden CLI standalone binary if not present
# (npm package uses WASM which has getrandom incompatibility on Node.js)
if ! command -v bw &>/dev/null; then
    echo "Installing Bitwarden CLI (standalone binary)..."
    mkdir -p "$HOME/.local/bin"
    curl -fsSL "https://vault.bitwarden.com/download/?app=cli&platform=linux" -o /tmp/bw.zip
    unzip -o /tmp/bw.zip bw -d "$HOME/.local/bin/"
    chmod +x "$HOME/.local/bin/bw"
    rm -f /tmp/bw.zip
    export PATH="$HOME/.local/bin:$PATH"
fi

# Login if unauthenticated
STATUS=$(bw status | jq -r '.status')
if [ "$STATUS" = "unauthenticated" ]; then
    echo "Not logged in. Starting Bitwarden login..."
    bw login --passwordenv BW_PASSWORD
fi

# Unlock and capture session token (BW_PASSWORD is used automatically)
SESSION=$(bw unlock --passwordenv BW_PASSWORD --raw)
if [ -z "$SESSION" ]; then
    echo "Error: Bitwarden unlock failed." >&2
    exit 1
fi
export BW_SESSION="$SESSION"

bw sync --session "$BW_SESSION" > /dev/null
echo "Bitwarden synced."

# Resolve api_keys folder ID
FOLDER_ID=$(bw list folders --session "$BW_SESSION" | jq -r '.[] | select(.name == "api_keys") | .id')
if [ -z "$FOLDER_ID" ]; then
    echo "Error: Folder 'api_keys' not found." >&2
    exit 1
fi

# Fetch items in folder
ITEMS=$(bw list items --folderid "$FOLDER_ID" --session "$BW_SESSION")
ITEM_COUNT=$(echo "$ITEMS" | jq 'length')
echo "Found $ITEM_COUNT items in 'api_keys'."

# Write secrets to ~/.secrets (login.password > notes > matched custom field)
{
    echo "# Auto-generated by initialize_security.sh — do not edit manually"
    echo "$ITEMS" | jq -r '.[] |
        .name as $name |
        (
            if .login.password != null and .login.password != "" then .login.password
            elif .notes != null and .notes != "" then .notes
            else (
                (.fields // []) |
                map(select(
                    .name != null and
                    (.name | ascii_downcase | test("value|api_key|secret|password|key"))
                )) |
                first |
                .value // empty
            )
            end
        ) as $value |
        select($value != null and $value != "") |
        "export \($name)=\"\($value)\""'
} > "$SECRETS_FILE"
chmod 600 "$SECRETS_FILE"

# Ensure ~/.secrets is auto-loaded in new shells
BASHRC_SOURCE_LINE='[ -f "$HOME/.secrets" ] && source "$HOME/.secrets"'
if ! grep -qF '.secrets' "$HOME/.bashrc" 2>/dev/null; then
    {
        echo ""
        echo "# Load API keys (written by initialize_security.sh)"
        echo "$BASHRC_SOURCE_LINE"
    } >> "$HOME/.bashrc"
    echo "Added source line to ~/.bashrc"
else
    echo "~/.bashrc already sources ~/.secrets — skipped."
fi

SAVED=$(grep -c '^export ' "$SECRETS_FILE" || true)
echo ""
echo "--- Summary ---"
echo "$SAVED secret(s) written to $SECRETS_FILE"
echo ""
echo "Loaded variables:"
grep '^export ' "$SECRETS_FILE" | sed 's/^export \([^=]*\)=.*/\1/' | while read -r varname; do
    echo "  $varname"
done
echo ""
echo "Run: source ~/.bashrc  (または新しいターミナルを開いてから Claude Code を再起動)"
